/*
 * CameraSub.h
 *
 *  Created on: Jan 18, 2018
 *      Author: frc5096
 */
#ifndef CAMERASUB_H
#define CAMERASUB_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include <CameraServer.h>
#include <string>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>


//#include "OI.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class CameraSub: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//	cs::UsbCamera camera0;
//	cs::UsbCamera camera1;

public:
	CameraSub();
	void InitDefaultCommand();
	void VisionThread();
	std::shared_ptr<NetworkTable> table;
//	std::shared_ptr<frc::CameraServer> usbCamera1;
//	std::shared_ptr<cs::UsbCamera> frontCamera;
//	std::shared_ptr<BlobAndContour> targetACK;


//	std::shared_ptr<frc::CameraServer> cameraServer();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif /* SRC_SUBSYSTEMS_CAMERASUB_H_ */
