// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Gripping.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Gripping::Gripping(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Gripping::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Gripping::Execute() {
	if(Robot::oi->joy2Button1->Get()==true)
	{
		Robot::arm->OpenGripper();
		frc::SmartDashboard::PutBoolean("Open", Robot::oi->joy2Button1->Get());
	}
	else
		Robot::arm->CloseGripper();
		frc::SmartDashboard::PutBoolean("Close", Robot::oi->joy2Button2->Get());


}

// Make this return true when this Command no longer needs to run execute()
bool Gripping::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Gripping::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Gripping::Interrupted() {

}
