// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Chassis.h"
#include "Commands/Gripping.h"
#include "Commands/Hanging.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick1.reset(new frc::Joystick(0));
    joystick2.reset(new frc::Joystick(1));

    // SmartDashboard Buttons
//    frc::SmartDashboard::PutData("Gripping", new Gripping());
  //  frc::SmartDashboard::PutData("Hanging", new Hanging());
    //frc::SmartDashboard::PutData("Chassis", new Chassis());
    //frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    joy1Button1.reset(new JoystickButton(joystick1.get(),1));   //Nothing
    joy1Button2.reset(new JoystickButton(joystick1.get(),2));   //Nothing
    joy1Button3.reset(new JoystickButton(joystick1.get(),3));   //Nothing
    joy2Button1.reset(new JoystickButton(joystick2.get(),1));   //Close Gripper
    joy2Button2.reset(new JoystickButton(joystick2.get(),2));   //Open Gripper
    joy2Button10.reset(new JoystickButton(joystick2.get(),10)); //Start Hanging
    joy2Button11.reset(new JoystickButton(joystick2.get(),11)); //Stop Hanging

    joyButtontrigger.reset(new JoystickButton(joystick2.get(),1));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystick1() {
   return joystick1;
}

std::shared_ptr<frc::Joystick> OI::getJoystick2(){
	return joystick2;
}



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
