// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	//
	

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	std::shared_ptr<frc::Joystick> joystick1;
	std::shared_ptr<frc::Joystick> joystick2;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> getJoystick1();
	std::shared_ptr<frc::JoystickButton> joy1Button1;
	std::shared_ptr<frc::JoystickButton> joy1Button2;
	std::shared_ptr<frc::JoystickButton> joy1Button3;
	std::shared_ptr<frc::JoystickButton> joy2Button1;
	std::shared_ptr<frc::JoystickButton> joy2Button2;
	std::shared_ptr<frc::JoystickButton> joy2Button10;
	std::shared_ptr<frc::JoystickButton> joy2Button11;
	std::shared_ptr<frc::Joystick> getJoystick2();
	std::shared_ptr<frc::JoystickButton> joyButtontrigger;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
