// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<frc::SpeedController> drivingRightFront;
	static std::shared_ptr<frc::SpeedController> drivingLeftFront;
	static std::shared_ptr<frc::SpeedController> drivingLeftBack;
	static std::shared_ptr<frc::SpeedController> drivingRightBack;
	static std::shared_ptr<frc::SpeedController> armMotor;
	static std::shared_ptr<frc::RobotDrive> drivingRobotDrive41;
	static std::shared_ptr<frc::Compressor> armCompressor1;
	static std::shared_ptr<frc::Relay> armArm;
	static std::shared_ptr<frc::Relay> armRightGrip;
	static std::shared_ptr<frc::Relay> armLeftGrip;
	static std::shared_ptr<frc::BuiltInAccelerometer> accelCop1;
	static std::shared_ptr<frc::Solenoid> armrightSolenoid;
	static std::shared_ptr<frc::Solenoid> armleftSolenoid;

	static std::shared_ptr<frc::ADXRS450_Gyro> drivingGyro;
	static std::shared_ptr<frc::DigitalInput> raiseSwitch;
	static std::shared_ptr<frc::DigitalInput> lowerSwitch;
	static std::shared_ptr<frc::DigitalInput> upperHangSwitch;
	static std::shared_ptr<frc::DigitalInput> lowerHangSwitch;
	static std::shared_ptr<frc::SpeedController> climbMotor;
	static std::shared_ptr<AnalogInput> rangeFinder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
