// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
//OtherCommands
#include "Commands/AutonomousCommand.h"
#include "Subsystems/Accel.h"
#include "Subsystems/Arm.h"
#include "Subsystems/Climbing.h"
#include "Subsystems/Driving.h"
#include "Subsystems/CameraSub.h"
#include "Commands/Chassis.h"
#include "Commands/Delay.h"
#include "Commands/ApproachTarget.h"
#include "Commands/JogForward.h"
#include "Commands/ArmCommand.h"
//Autonomous
#include "Commands/AM_C_CloseSwitch_Left.h"
#include "Commands/AM_C_CloseSwitch_Right.h"
#include "Commands/AM_C_CrossTheLine.h"
#include "Commands/AM_C_ExchangeCube.h"
#include "Commands/AM_C_FarSwitch_Left.h"
#include "Commands/AM_C_FarSwitch_Right.h"
#include "Commands/AM_C_Scale_Left.h"
#include "Commands/AM_C_Scale_Right.h"

#include "Commands/AM_L_CloseSwitch_Left.h"
#include "Commands/AM_L_CloseSwitch_Right.h"
#include "Commands/AM_L_CrossTheLine.h"
#include "Commands/AM_L_ExchangeCube.h"
#include "Commands/AM_L_FarSwitch_Left.h"
#include "Commands/AM_L_FarSwitch_Right.h"
#include "Commands/AM_L_Scale_Left.h"
#include "Commands/AM_L_Scale_Right.h"

#include "Commands/AM_R_CloseSwitch_Left.h"
#include "Commands/AM_R_CloseSwitch_Right.h"
#include "Commands/AM_R_CrossTheLine.h"
#include "Commands/AM_R_ExchangeCube.h"
#include "Commands/AM_R_FarSwitch_Left.h"
#include "Commands/AM_R_FarSwitch_Right.h"
#include "Commands/AM_R_Scale_Left.h"
#include "Commands/AM_R_Scale_Right.h"

#include "Commands/DoNothing.h"




    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot : public frc::TimedRobot {
public:
	frc::Command* autonomousCommand = nullptr;
	static std::unique_ptr<OI> oi;
	frc::LiveWindow *lw = frc::LiveWindow::GetInstance();
	frc::SendableChooser<frc::Command*> chooser;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<Driving> driving;
	static std::shared_ptr<Climbing> climbing;
	static std::shared_ptr<Arm> arm;
	static std::shared_ptr<Accel> accel;
	static std::shared_ptr<CameraSub> camerasub;
	std::unique_ptr<Command> chassis;
	std::unique_ptr<Command> armcommand;
	std::unique_ptr<Command> selected;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	void RobotInit() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;
	int m_autocommand;
	int m_positionchooser;
	bool m_done;
	cs::UsbCamera cam0;
	cs::UsbCamera cam1;
	std::string gameData;
};
#endif
